name: Auto Tag on Merge

on:
  # Should trigger only when a Pull Request is Closed
  # (the action will not create the Tag if the Pull Request is discarded - closed without merge)
  pull_request:
    types:
      - closed
    branches:
      - master
      
permissions:
  contents: write  # Grant permission to push changes (tags)
  
jobs:
  TagOnPR:
    name: Tag on Pull Request merge
    runs-on: ubuntu-latest
    # This 'if' condition ensures the workflow only runs for merged PRs
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Generate Tag
        id: tag
        run: |
          # Generate a tag name based on the current date and the PR number
          TAG_NAME="v$(date +'%Y%m%d')-pr${{ github.event.pull_request.number }}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          # Create and push the new tag
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Print the created tag
        run: |
          echo "Created tag: $TAG_NAME"
